apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-consul-storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-consul-storage
  local:
    path: /home/patrick/Local K8S Cluster/Storage Directory/Consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - patrick358