apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-helm
  namespace: "{{- .Values.argoNamespace}}"
spec:
  project: "{{- .Values.project }}"
  source:
    repoURL: "{{- .Values.source.repoURL }}"
    targetRevision: "{{- .Values.source.targetRevision }}"
    path: "{{- .Values.baseManifestPath }}/consul-helm-chart"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "{{- .Values.targetCluster }}"
    namespace: "{{- .Values.namespace }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false