apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/patrickgatiri/ArgoCD-Deployment.git
    targetRevision: HEAD
    path: argocd/security
    helm:
      valueFiles:
        - ../../values.global.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true