apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: "{{- .Values.project }}"
  source:
    repoURL: "{{- .Values.source.repoURL }}"
    targetRevision: "{{- .Values.source.targetRevision }}"
    path: manifests/security/banzai-cloud-vault/vault-operator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "{{- .Values.targetCluster }}"
    namespace: "{{- .Values.namespace }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false