apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-apps
  namespace: "{{- .Values.argoNamespace}}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: "{{- .Values.project }}"
  source:
    repoURL: "{{- .Values.source.repoURL }}"
    targetRevision: "{{- .Values.source.targetRevision }}"
    path: argocd/frontend
    helm:
      valueFiles:
        - ../values.global.yaml
        - values.yaml
  destination:
    server: "{{- .Values.targetCluster }}"
  syncPolicy:
    automated:
      prune: "{{- .Values.prune}}"
      selfHeal: "{{- .Values.selfHeal}}"
    syncOptions:
      - CreateNamespace=false